WIP add individual scale exports
OpenBeta/sandbag pull request #106
Opened 2023-04-27 16:15 UTC by actuallyyun

I am using this branch to test exports work properly using codesandbox

2023-04-28 15:28 UTC, vicjor approved these changes

2023-04-28 22:30 UTC, musoke commented
> I was thinking, for the `convertGrade` function, maybe we should use uppercase to keep the naming consistent. What do you think? @musoke

Are you thinking `ConvertGrade` instead of `convertGrade`?  Would be a breaking change, so let's discuss in a separate issue.

2023-04-28 23:03 UTC, musoke commented
The new exports look good.

Is there some way to verify that the examples run in `yarn test`?  Then they won't go out of sync with any further changes to the API.

2023-05-02 08:30 UTC, actuallyyun commented
> > I was thinking, for the `convertGrade` function, maybe we should use uppercase to keep the naming consistent. What do you think? @musoke
> 
> Are you thinking `ConvertGrade` instead of `convertGrade`? Would be a breaking change, so let's discuss in a separate issue.

I see,then better not to make the change now.

2023-05-02 08:31 UTC, actuallyyun commented
> The new exports look good.
> 
> Is there some way to verify that the examples run in `yarn test`? Then they won't go out of sync with any further changes to the API.

You mean create a test file to test all the examples?

2023-05-02 15:04 UTC, musoke commented
> 
> You mean create a test file to test all the examples?

Yes, but let's leave that for later.

2023-05-03 10:37 UTC, musoke requested changes
Please change `converGrade` to `convertGrade` and `GradeScales.VScale` to `GradeScales.VSCALE`

2023-05-03 10:37 UTC, musoke commented on README.md
> +const fontInVScale=converGrade('6a',GradeScales.FONT,GradeScales.VScale) //OutPut 'V3'
`converGrade` should be `convertGrade`

2023-05-03 10:37 UTC, musoke commented on README.md
> +const fontInVScale=converGrade('6a',GradeScales.FONT,GradeScales.VScale) //OutPut 'V3'
Is there some way to verify that the examples run in `yarn test`? Maybe put them in individual scripts in `./examples/` and get jest to run them?  This will catch these errors and CI will flag them if they go out of sync with changes to the API.  That can wait if it's going to be tricky.

2023-05-03 10:37 UTC, musoke commented on README.md
> +const fontInVScale=converGrade('6a',GradeScales.FONT,GradeScales.VScale) //OutPut 'V3'
`GradeScales.VScale` should be `GradeScales.VSCALE`

2023-05-03 12:45 UTC, actuallyyun commented on README.md
> +const fontInVScale=converGrade('6a',GradeScales.FONT,GradeScales.VScale) //OutPut 'V3'
Ok, I will look into it.

2023-05-03 15:15 UTC, musoke approved these changes

2023-05-03 15:18 UTC, musoke commented
Looks good!  You even rebased and squashed.

Export Saxon (new in https://github.com/OpenBeta/sandbag/pull/108) and merge it.

2023-05-03 16:12 UTC, merged

2023-05-03 16:15 UTC, musoke commented
@all-contributors add @actuallyyun  for code & ideas