added Norwegian (aka Scandanavian) grades
OpenBeta/sandbag pull request #118
Opened 2023-06-06 18:28 UTC by josh610

[Issue #102](https://github.com/OpenBeta/sandbag/issues/102)

Grade conversions were done via [this](https://www.thecrag.com/en/article/grades) converter from TheCrag.com

2023-06-06 21:03 UTC, musoke commented
Thanks!  I'll take a look.

2023-06-07 11:38 UTC, musoke commented
Let's settle on one name used everywhere.  Probably one of
- Norwegian
- Norway
- Scandanavian

It's my understanding that Norwegian and Swedish grades are in principle different, so I would discount the last.  "Norwegian" rather than "Norway" seems more consistent with colloquial use and with "French" instead of "France".  What do you think?

2023-06-07 11:42 UTC, musoke requested changes
This looks good!  I left a couple small comments to address.

2023-06-07 11:42 UTC, musoke commented on src/GradeScale.ts
> +  NORWAY: 'norwegian'
Let's use a consistent name everywhere.

2023-06-07 11:42 UTC, musoke commented on src/index.ts
> +// Norwegian (aka Scandinavian)
Could you remove this comment and the one for NOR? This is a list of grades we don't have yet.

2023-06-07 11:50 UTC, musoke commented
Was there anything about our processes that could be improved?  Is there anything we could add to docs to make writing this smoother for you?

2023-06-19 14:37 UTC, josh610 commented on src/GradeScale.ts
> +  NORWAY: 'norwegian'
Settled on "Norwegian"

2023-06-19 14:40 UTC, josh610 commented
> 

To be honest, I'm not super familiar with a lot of the software and processes that Sandbag / OpenBeta uses, so I don't think I can offer constructive criticism. That being said, it seemed pretty straightforward to me.

2023-06-19 16:28 UTC, musoke approved these changes

2023-06-19 16:30 UTC, merged

2023-06-19 16:31 UTC, musoke commented
Thank you @josh610!

@all-contributors add @josh610  for code